sudo: required
services:
    - docker

before_install:
    - docker build -t skpradeep/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true skpradeep/docker-react npm run test -- --coverage